name: Process Modpack Updates

on:
    workflow_dispatch:
        inputs:
            base_ref:
                description: "基准提交哈希"
                required: false
                default: ""
            compare_ref:
                description: "比较提交哈希"
                required: false
                default: ""
            ref:
                description: "Mierno 仓库引用（分支/标签）"
                default: "main"
                required: true

jobs:
    process-updates:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Mierno-updater repository
              uses: actions/checkout@v4
              with:
                  path: updater-repo
                  token: ${{ secrets.MODPACK_UPDATER_TOKEN }}
                  fetch-depth: 0 # 确保获取完整历史以便后续操作

            - name: Checkout Mierno repository
              uses: actions/checkout@v4
              with:
                  repository: FalAut/Mierno
                  ref: ${{ github.event.inputs.ref }}
                  fetch-depth: 0 # 获取完整历史以支持任意提交比较
                  path: mel-repo
                  token: ${{ secrets.MODPACK_UPDATER_TOKEN }}

            - name: Get versions
              id: version
              working-directory: mel-repo
              run: |
                  # 设置基准提交
                  if [ "${{ github.event.inputs.base_ref }}" != "" ]; then
                    BASE_COMMIT=${{ github.event.inputs.base_ref }}
                  else
                    BASE_COMMIT=$(git rev-parse HEAD^)
                  fi

                  # 设置比较提交
                  COMPARE_COMMIT=${{ github.event.inputs.compare_ref }}
                  if [ -z "$COMPARE_COMMIT" ]; then
                    COMPARE_COMMIT=$(git rev-parse HEAD)
                  fi

                  # 提取基准提交的版本
                  PREV_VERSION=$(git show $BASE_COMMIT:CHANGELOG.md | sed -n '/^##\s*v[0-9]/p' | head -n1 | sed 's/^## v//')
                  # 提取比较提交的版本
                  LATEST_VERSION=$(git show $COMPARE_COMMIT:CHANGELOG.md | sed -n '/^##\s*v[0-9]/p' | head -n1 | sed 's/^## v//')

                  echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_OUTPUT
                  echo "PREV_VERSION=${PREV_VERSION}" >> $GITHUB_OUTPUT
                  echo "BASE_COMMIT=${BASE_COMMIT}" >> $GITHUB_OUTPUT
                  echo "COMPARE_COMMIT=${COMPARE_COMMIT}" >> $GITHUB_OUTPUT

            - name: Debug version variables
              run: |
                  echo "PREV_VERSION: ${{ steps.version.outputs.PREV_VERSION }}"
                  echo "LATEST_VERSION: ${{ steps.version.outputs.LATEST_VERSION }}"
                  echo "BASE_COMMIT: ${{ steps.version.outputs.BASE_COMMIT }}"
                  echo "COMPARE_COMMIT: ${{ steps.version.outputs.COMPARE_COMMIT }}"

            - name: Find changed files
              id: changed_files
              working-directory: mel-repo
              run: |
                  BASE_REF=${{ steps.version.outputs.BASE_COMMIT }}
                  COMPARE_REF=${{ steps.version.outputs.COMPARE_COMMIT }}

                  # 查找修改和添加的文件
                  MODIFIED_FILES=$(git diff --name-only --diff-filter=M $BASE_REF $COMPARE_REF | grep -E "^(config|defaultconfigs|hotai|kubejs|ldlib)/" || true)
                  ADDED_FILES=$(git diff --name-only --diff-filter=A $BASE_REF $COMPARE_REF | grep -E "^(config|defaultconfigs|hotai|kubejs|ldlib)/" || true)
                  # 查找删除的文件
                  DELETED_FILES=$(git diff --name-only --diff-filter=D $BASE_REF $COMPARE_REF | grep -E "^(config|defaultconfigs|hotai|kubejs|ldlib)/" || true)

                  if [ -n "$MODIFIED_FILES" ] || [ -n "$ADDED_FILES" ] || [ -n "$DELETED_FILES" ]; then
                    # 保存修改和添加的文件
                    echo "modified_files<<EOF" >> $GITHUB_OUTPUT
                    echo "$MODIFIED_FILES" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT

                    echo "added_files<<EOF" >> $GITHUB_OUTPUT
                    echo "$ADDED_FILES" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT

                    # 保存删除的文件
                    echo "deleted_files<<EOF" >> $GITHUB_OUTPUT
                    echo "$DELETED_FILES" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT

                    echo "changes_detected=true" >> $GITHUB_OUTPUT
                  else
                    echo "changes_detected=false" >> $GITHUB_OUTPUT
                  fi

            - name: Process changed files and generate hashes
              if: steps.changed_files.outputs.changes_detected == 'true'
              run: |
                  cd mel-repo

                  mkdir -p "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}"
                  mkdir -p "../updater-repo/hashes/${{ steps.version.outputs.PREV_VERSION }}"

                  # 处理修改和添加的文件
                  if [ -n "${{ steps.changed_files.outputs.modified_files }}" ]; then
                    echo "${{ steps.changed_files.outputs.modified_files }}" | while IFS= read -r file; do
                      if [ ! -z "$file" ]; then
                        mkdir -p "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$(dirname "$file")"
                        cp "$file" "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$file"
                        HASH=$(sha256sum "$file" | awk '{print $1}')
                        echo "$file|$HASH" >> "../updater-repo/hashes/${{ steps.version.outputs.PREV_VERSION }}/hashes.txt"
                      fi
                    done
                  fi

                  if [ -n "${{ steps.changed_files.outputs.added_files }}" ]; then
                    echo "${{ steps.changed_files.outputs.added_files }}" | while IFS= read -r file; do
                      if [ ! -z "$file" ]; then
                        mkdir -p "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$(dirname "$file")"
                        cp "$file" "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$file"
                        HASH=$(sha256sum "$file" | awk '{print $1}')
                        echo "$file|$HASH" >> "../updater-repo/hashes/${{ steps.version.outputs.PREV_VERSION }}/hashes.txt"
                      fi
                    done
                  fi

                  # 处理删除的文件 - 创建空文件
                  if [ -n "${{ steps.changed_files.outputs.deleted_files }}" ]; then
                    echo "${{ steps.changed_files.outputs.deleted_files }}" | while IFS= read -r file; do
                      if [ ! -z "$file" ]; then
                        mkdir -p "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$(dirname "$file")"
                        touch "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$file"
                        # 为空文件生成哈希
                        HASH=$(sha256sum "../updater-repo/hotfixes/${{ steps.version.outputs.PREV_VERSION }}/$file" | awk '{print $1}')
                        echo "$file|$HASH" >> "../updater-repo/hashes/${{ steps.version.outputs.PREV_VERSION }}/hashes.txt"
                      fi
                    done
                  fi

            - name: Extract changelog
              working-directory: mel-repo
              run: |
                  mkdir -p "../updater-repo/versions/${{ steps.version.outputs.LATEST_VERSION }}"
                  sed -n "/^## v${{ steps.version.outputs.LATEST_VERSION }}/,/^## /p" CHANGELOG.md | sed '$d' > "../updater-repo/versions/${{ steps.version.outputs.LATEST_VERSION }}/changelog.txt"

            - name: Update meta.json
              working-directory: updater-repo
              run: |
                  if [ ! -f meta.json ]; then
                    echo '{"schemaVersion":1,"hotfixesFormat":null,"versions":[]}' > meta.json
                  fi

                  TIMESTAMP=$(date +%s%3N)
                  VERSION="${{ steps.version.outputs.LATEST_VERSION }}"

                  # 创建新的版本条目
                  NEW_VERSION=$(cat <<EOF
                  {
                    "id": "$VERSION",
                    "releasedAt": $TIMESTAMP,
                    "promotions": {
                      "downloads": {
                        "generic": "https://github.com/FalAut/Mierno/releases/download/v${VERSION}/Mierno-${VERSION}.zip"
                      }
                    },
                    "updateType": "minor"
                  }
                  EOF
                  )

                  # 更新 meta.json
                  jq --argjson new "$NEW_VERSION" '.versions += [$new]' meta.json > meta.json.tmp
                  mv meta.json.tmp meta.json

            - name: Commit and push changes
              working-directory: updater-repo
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git remote set-url origin https://x-access-token:${{ secrets.MODPACK_UPDATER_TOKEN }}@github.com/FalAut/Mierno-updater.git

                  git add .
                  git commit -m "Update for version ${{ steps.version.outputs.LATEST_VERSION }}" || echo "No changes to commit"
                  git push
